# 在主分支上构建 Vue 页面
name: build-vue
on:
  push: # push 触发
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    # 拉取代码
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    # 设置 Node.js 版本
    - name: Load Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    # 更新依赖
    - name: Install
      run: yarn
    # 替换构建配置
    - name: Replace config
      run: |
        rm vue.config.js
        mv vue.config.action.js vue.config.js
        cat vue.config.js
    # 构建
    - name: Build
      run: yarn build

    # 部署
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: dist
